# Generated by Django 4.2.7 on 2023-12-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_item_dislikes_item_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='availablity',
            field=models.BooleanField(default=True),
        ),
    ]
